### ISSUE TITLE
gl_PointSize with fixed world coordinates size (10mm)

### ISSUE THREAD

**Issue by ua4192** [cnr-isti-vclab/nexus#101]
Hi.

I am trying to desing a glsl shader code in which my points have a fixed real coords size, for example 10mm
My world coords unit size is 1mm.

This is my approach:

My shader:
```
var vertexShader = `
			precision highp float;
			in vec3 color;
			//in vec2 uv;
			out vec3 vColor;
			uniform sampler2D texture;
			uniform float textureSize;
			uniform float mode;
			uniform vec3 pointInfo;
			#include <common>                  
			#include <logdepthbuf_pars_vertex> 
			
			float getUuid(vec3 col) {
				return round(col.r*255.0)*65536.0 + round(col.g*255.0)*256.0 + round(col.b*255.0);
			}                                                                          
			void main() {
				float pn_UUID =  float(  round(color.r*255.0)*65536.0 + round(color.g*255.0)*256.0 + round(color.b*255.0)  );
				float tsize = textureSize;
				ivec2 coords = ivec2( int(mod(pn_UUID, tsize)), int(floor(pn_UUID / tsize)) ) ;
				vec4 values = texelFetch(texture, coords, 0);
				vec4 tPosition = vec4( position, 1.0 ); 
				vec4 kPosition = viewMatrix * tPosition;
				if ( mode == 0.0) {
					vColor = color;
				} else if (mode == 1.0){
					vColor = values.rgb;
				} else {
					vColor = color.rgb;
				}
				vec4 modelViewPosition = modelViewMatrix * vec4(position, 1.0);
				gl_Position = projectionMatrix * viewMatrix * tPosition;
				float distance2 = distance(tPosition.xyz, cameraPosition);
				gl_PointSize = floor(pointInfo[0]/(distance2*abs(sin(pointInfo[1]/2.0))/pointInfo[2]));
				#include <logdepthbuf_vertex>
			}
		`;
```

My uniforms:
```
var pointInfo = new THREE.Vector3(canvas_w/pointDivFactor, cameraFov, pointSize);
var pointsUniforms = {
			mode: {value: 0},
			textureSize: {value: side},
			texture: { value: texture },
			pointInfo: { value: pointInfo}
		};
My material:
var pointsShadermaterial = new THREE.ShaderMaterial({
			uniforms: pointsUniforms,
			vertexShader: "#version 300 es\n" + vertexShader,
			fragmentShader: "#version 300 es\n" +fragmentShader,
			side: THREE.DoubleSide
		});
```

But I dont get the expected behaviour.

Could anybody help me?

Best regards

**Comment by ponchio** [comment]
Hi, It's a bit hard to help you as I can only guess what some variables are:

pointSize (pointInfo[2])) I suppose is the size of the pixel in mm.
canvas_w/pointDivFactor is the number of pixels in the viewport
(horizontal).

and I don't know what's is the unexpected behavior.

Assuming tPosition and cameraPosition are in the same world coordinate
system, everything seems more or less correct still I see a couple of
problems:

1) pointInfo[0] seems to be the whole viewport while distance2*sin(fov/2)
is only half of the viewport (why abs anyway, it should always be positive)

2) the correct formula for the center of the screen would be tan, not sin,
and for large fov this could be pretty different.

3) when you move to the boundary of the screen the geometry get
distorted (a circle becomes an ellipse) but the splats
remain circles, so vertical and horizontal distance cannot be faithful at
the same time (if you care about this approximation).


I hope this helps.

**Comment by ua4192** [comment]
Hi Federico

Your asumptions are correct.

I will try with tan formula.

Many many thanks
