### ISSUE TITLE
Building nxszip

### ISSUE THREAD

**Issue by antonkarasu** [cnr-isti-vclab/nexus#103]
The requirements for building nxszip are unclear - am I missing a library? I get :

WARNING: Failure to find: watch.cpp
WARNING: Failure to find: mesh_coder.cpp
WARNING: Failure to find: mesh_coder.h
WARNING: Failure to find: watch.h
WARNING: Failure to find: geometry_coder.h
WARNING: Failure to find: connectivity_coder.h

**Comment by ponchio** [comment]
The nxszip is just a leftover from a refactoring: the compression is handled in nxsedit with otpion -z.
I just need to remove it. Sorry for the confusion.
