### ISSUE TITLE
Texture packed in NXS larger than 16k

### ISSUE THREAD

**Issue by brunodutailly** [cnr-isti-vclab/nexus#105]
I build a NXS from a PLY with a texture 16000 x 16000.
When I load this NXS in 3DHop, a texture patch appears black. I debug in the code of 3DHop that a texture taken from the NXS is 1991 x 17514, and the gl.texImage2D failed.
I manage to scale the texture on the fly in3DHop to 16384, but some UV artifacts appears.
Is there any way to control textures patches size?
Thanks.

**Comment by ponchio** [comment]
Usually this happens when the ratio between number of triangle and number of pixel is very low.
You can decrease the size of the patches (option -f).

This also happens when the parametrization is really bad, since nxsbuild try to preserve the parametrization but packing is a bit naive, so if the parametrization is fragmented and the islands are non convex some space is wasted. Sometime a lot of space.

**Comment by brunodutailly** [comment]
Ok, I tried to decrease the face count per patch (-f). It decreases the size of the black patch, but it didn't disappear. (tried 1000, 1024, 4096, 8192).

Also, it seems that the UV artifacts were already there before I scale the texture in 3DHop. Maybe another issue on UV islands borders.

Anyway thanks for helping me.

**Comment by ponchio** [comment]
If you can share the model, I can have a look and figure out what is
happening. ***@***.***)

**Comment by brunodutailly** [comment]
After some tests, I manage to understand what was wrong:
My original model (PLY) has texture with UVs, and the artifact were located on the border of an island which is also on the border of the texture (the image itself).
I have exported the PLY to OBJ, find and replace in UV : 1.000000 to 0.999999. Export back to PLY, convert to NXS, and load in 3DHop and it is good. There were also UVs at 0.000000 but no problem with them.
FYI, artifacts appears only in 3DHop, neither in NXSViewer nor in meshlab. So I assume it is related to 3DHop and how they deal with UVs on image border.
