### ISSUE TITLE
Fatal error: virtual memory error mapping block: Access is denied

### ISSUE THREAD

**Issue by ua4192** [cnr-isti-vclab/nexus#108]
Hi Federico.

I am getting sometimes this eror when converting from ply to nxs.

And sometime I don't get any error but the nxsbuild.exe command does nothing, only says:
Reading <File>.ply

Let me attach you some files in a ZIP.

[200.zip](https://github.com/cnr-isti-vclab/nexus/files/6625236/200.zip)

Many thanks in advanced for your great support.

Best regards

**Comment by ponchio** [comment]
It looks like the .ply triangles have some 'bad' index: too large for the existing number of vertices.

I have added a check for it, so at least you know it :)

**Comment by ua4192** [comment]
Hello.

Many thanks. I figured out that problem should be in ply files.

Sorry for bothering you again.

Best regards.

**Comment by Roger-Rapp** [comment]
Hi!
I just got the same fatal error message using NEXUS 4.3 nxsbuild. Didn't see any other hints on the command line, so was glad to see some discussion about it here. 

I tried a few of MeshLab's repair options but it's a 1GB ply so trying is pushing my laptop to its limit. 
Any advice would be welcomed.

Best,
Roger
