### ISSUE TITLE
Three.js r129 error : Uncaught (in promise) TypeError: Class constructor Mesh cannot be invoked without 'new'

### ISSUE THREAD

**Issue by gribouille139** [cnr-isti-vclab/nexus#109]
Hye, 
I tried to upgrade to r129 from r124 of Three.js
I got this error : 
![image](https://user-images.githubusercontent.com/73525724/122765543-e5fb8b00-d2a0-11eb-9512-35ebf0e4d636.png)
![image](https://user-images.githubusercontent.com/73525724/122765585-f27fe380-d2a0-11eb-89c2-4efaf1a1e6f1.png)
Any idea to solve it ?
thanks

**Comment by ponchio** [comment]
I have updated the nexus_three.js to release 130.
