### ISSUE TITLE
Nexus fails when converting model with textures

### ISSUE THREAD

**Issue by josefrcm** [cnr-isti-vclab/nexus#11]
We are using Nexus and 3DHop to develop a web app, with very good results, it's a really good software. However, we have found that sometimes nxsbuild fails when given a textured PLY file. It seems that some software add unnecesary whitespace around the texture file name, and Nexus doesn't trim that whitespace, so it tries to find a file that doesn't exist.

We have found a solution: just replace line 120 of file _src/nxsbuild/plyloader.cpp_ from this
`texture_filenames.push_back(buf2);`
to this
`texture_filenames.push_back(QString(buf2).trimmed());`

**Comment by ponchio** [comment]
Thank you for the feedback :)
