### ISSUE TITLE
Texture bug in threejsES6 branch for Firefox version > 93.0

### ISSUE THREAD

**Issue by jfeick** [cnr-isti-vclab/nexus#116]
Hello @ponchio 
Firefox changed the default behavior of createImageBitmap (https://developer.mozilla.org/en-US/docs/Web/API/createImageBitmap) since version 93.0
See here: https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/93#javascript

This results in flipped textures that are created in the branch that explicitly checks for firefox (by some dubious method):
https://github.com/cnr-isti-vclab/nexus/blob/d59f327807bec05377d5eb41b53c757c1d4b1a93/nexus3d/src/Cache.js#L247

FF93+ would need to branch into the call with the option property for `imageOrientation` 
https://github.com/cnr-isti-vclab/nexus/blob/d59f327807bec05377d5eb41b53c757c1d4b1a93/nexus3d/src/Cache.js#L249

I don't know how to differentiate FF versions without resorting to user agent parsing which I think is a very unelegant solution.
Perhaps earlier FF version support should be dropped altogether?

**Comment by ponchio** [comment]
Earlier versions of Firefox would raise an exception on passing options, I just added a try/catch fallback for older version (to be tested though).

Thanks for the issue report.
