### ISSUE TITLE
Crashes unexpectedly

### ISSUE THREAD

**Issue by garynobles** [cnr-isti-vclab/nexus#12]
Unable to process landscape models like the one attached. Opens fine in blender and mesh lap.
Version 4.1.6 (same issue in 4.1.5)
It creates the cache_stream file then crashes. I'm having the same issue on a few files.
[trim_castle.zip](https://github.com/cnr-isti-vclab/nexus/files/1282565/trim_castle.zip)

The textures were in a different file, so fixed, please delete this issue.

**Comment by ponchio** [comment]
It should report an error, not crash... but it does, maybe not the last version of the excutables.
