### ISSUE TITLE
Can't compile nxscompress on linux (ubuntu 20.04)

### ISSUE THREAD

**Issue by radicalreflect** [cnr-isti-vclab/nexus#131]
Hi there,

after successful compilation of nxsedit, nxsview, nxsbuild – i got a compiler error for nxscompress.

g++ -Wl,-O1 -o ../../bin/nxscompress qgetopt.o plylib.o virtualarray.o nexusdata.o traversal.o cone.o meshcoder.o meshdecoder.o abitstream.o atunstall.o main_compress.o extractor.o   -L /usr/local/lib -lcorto /usr/lib/x86_64-linux-gnu/libQt5Gui.so /usr/lib/x86_64-linux-gnu/libQt5Core.so /usr/lib/x86_64-linux-gnu/libGL.so -lpthread
/usr/bin/ld: nexusdata.o: in function `nx::NexusData::NexusData()':
nexusdata.cpp:(.text+0x344): undefined reference to `vtable for nx::QTNexusFile'
collect2: error: ld returned 1 exit status
make: *** [Makefile:191: ../../bin/nxscompress] Error 1

is there any workaround or did i make a mistake?

Thank you in advance and for your outstanding work!

**Comment by ponchio** [comment]
Hi,
         nxscompress is actually just a shortcut executable for nxsedit
(which can also do other tasks)  and I forgot to update it when refactoring
some code.

Just use nxsedit (-z is to compress .nxs)

Sorry,

Federico
