### ISSUE TITLE
problem with glb file with RGBA color attribute

### ISSUE THREAD

**Issue by ua4192** [cnr-isti-vclab/nexus#132]
Hi Federico.

I hope you are fine.

I am trying to convert a glb file with color attribute composed by RGBA.

In order to no lose precission when converting to nxz I am using a Uint8Array as BufferAttribute with 4 components. I don't know if this is allowed by the convertor or I have to use normalizaed values inside a Float32Array. In any case I get the same error.

I am still using the compiled version you sent me some months ago because it seems that the compiled version availbale in GITHUB is still not supporting GLTF files.

My problem is that when I convert the file from glb to NXS --> NXZ with nxsbuild and nxsconvert it seems to be ok but when I try to see the model with your THREEJS api it prompts me this error:

nexus.js:407 Uncaught RangeError: Array buffer allocation failed
    at new ArrayBuffer (<anonymous>)
    at new Uint32Array (<anonymous>)
    at Mesh.handleIndex (nexus.js:407)
    at XMLHttpRequest.<anonymous> (nexus.js:394)
    at XMLHttpRequest.r.onload (nexus.js:376)

As it is not possible for me to send anything via github portal, I put you a very basic example:

This is how to reproduce error:

1.- create the scene	
	var scene = new THREE.Scene();
	var geo = new THREE.BoxBufferGeometry(10,10,10,10,10,10);
	var colors = new Uint8Array(geo.attributes.position.count*4)
	for (let i=0; i<colors.length; i++) {
		colors[i] = Math.floor(Math.random() * 255)
	}
	geo.attributes.color = new THREE.BufferAttribute(colors, 4, false)
	var mesh = new THREE.Mesh(geo);
	scene.add(mesh);
	
	export scene to box.glb
2.- Convert to nxz:
	nxedit box.glb -o box.nxs -C 
	nxsedit box.nxs -o box.nxz -z -C 8 -A 8

**Comment by ponchio** [comment]
Hi, 
    i don't know if I can manage to get your version, I think it would be way faster to just send me a sample (glb, nxs, nxz)  via email (ponchio@gmail.com (and the html + javascript minimal page).

   In any case the colors are saved in 8 bits even if you use floats, and the alpha is just set to 255 if you use only 3 rgb colors (for alignment purpouses).   
   The error seems of a completely different type (fail parsing the header of the .nxz)...

**Comment by ua4192** [comment]
Hi Federico.

I sent you the files via mail.

Please, if you don't mind, answer me here. I have no access to my email during weekends.

Many thanks in advanced.

**Comment by ponchio** [comment]
Ciao, 
          the glb you sent me does not seems to be fully conformant with the gltf specifications.
          Within meshes->primitives a material is defined directly as an object with its parameters instead of being an index into the materials array.
          
          The lib I am using for parsing the glb does not support this data structure: I have read the gltf specification and it is never mentioned as a possibility.
          
nxsbuilder actuatly report the error:

>       Invalid glTF document. See nested exception for details.

the problem is that the error is ignored and the conversion continues creating and empty .nxs.
The final reason for the error in the viewer is that it is trying to create an empty Uint32Array, which is invalid.

I will add this check, thanks for the feedback.

**Comment by ua4192** [comment]
Hi Federico.

I am using GLFExporter provided by THREEJS.
I will have a look on monday.

SOrry for bothering you wit my mistakes.

I have been trying to compile the latest release sing qmake, but I get an error message:

g++ -c -m64 -pipe -std=c++11 -g -fpermissive -O2 -Wall -W -D_REENTRANT -D_FILE_OFFSET_BITS=64 -D_USE_MATH_DEFINES -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I../../../vcglib -I../../../vcglib/eigenlib -I. -o objloader.o objloader.cpp
objloader.cpp: In member function ‘void ObjLoader::cacheTextureUV()’:
objloader.cpp:58:6: warning: unused variable ‘nidx’ [-Wunused-variable]
  int nidx = 0;
      ^~~~
objloader.cpp: In member function ‘void ObjLoader::readMTL()’:
objloader.cpp:93:28: error: no matching function for call to ‘QFileInfo::exists(QString&)’
   if(!QFileInfo::exists(mtl))
                            ^
In file included from /usr/include/qt4/QtCore/QFileInfo:1:0,
                 from objloader.cpp:19:
/usr/include/qt4/QtCore/qfileinfo.h:86:10: note: candidate: bool QFileInfo::exists() const
     bool exists() const;
          ^~~~~~
/usr/include/qt4/QtCore/qfileinfo.h:86:10: note:   candidate expects 0 arguments, 1 provided
objloader.cpp:103:28: error: no matching function for call to ‘QFileInfo::exists(QString&)’
  if (!QFileInfo::exists(mtl))
                            ^
In file included from /usr/include/qt4/QtCore/QFileInfo:1:0,
                 from objloader.cpp:19:
/usr/include/qt4/QtCore/qfileinfo.h:86:10: note: candidate: bool QFileInfo::exists() const
     bool exists() const;
          ^~~~~~
/usr/include/qt4/QtCore/qfileinfo.h:86:10: note:   candidate expects 0 arguments, 1 provided
objloader.cpp:88:10: warning: unused variable ‘pos’ [-Wunused-variable]
  quint64 pos = file.pos();
          ^~~
objloader.cpp: In member function ‘virtual quint32 ObjLoader::getTriangles(quint32, Triangle*)’:
objloader.cpp:331:23: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (int i = 0; i < texture_filenames.size(); i++) {
                     ~~^~~~~~~~~~~~~~~~~~~~~~~~~~
Makefile:342: recipe for target 'objloader.o' failed
make: *** [objloader.o] Error 1

May be I am m missing something?

Would it be possible to publish the last version compiled in github releases section?

Many thanks in advanced.

**Comment by ponchio** [comment]
Hi, probably not your mistake, probably more likely a threejs "extension" of gltf.

Next week I will try to post the exe in the release section, in your case the culprit is just an old version of Qt. ( use a recent 5.something version...)
