### ISSUE TITLE
Installation of nxscompress failed

### ISSUE THREAD

**Issue by pentaquarx** [cnr-isti-vclab/nexus#150]
Hi! I've some trouble installing nxscompress: 

```
$ qmake nxscompress.pro
$ make
g++ -Wl,-O1 -o ../../bin/nxscompress qgetopt.o plylib.o virtualarray.o nexusdata.o traversal.o cone.o meshcoder.o meshdecoder.o abitstream.o atunstall.o main_compress.o extractor.o   -L /usr/local/lib -lcorto /usr/lib/x86_64-linux-gnu/libQt5Gui.so /usr/lib/x86_64-linux-gnu/libQt5Core.so /usr/lib/x86_64-linux-gnu/libGL.so -lpthread   
/usr/bin/ld: nexusdata.o: in function `nx::NexusData::NexusData()':
nexusdata.cpp:(.text+0x344): undefined reference to `vtable for nx::QTNexusFile'
collect2: error: ld returned 1 exit status
make: *** [Makefile:191: ../../bin/nxscompress] Fehler 1
```

I adjusted `unix:INCLUDEPATH` in `nxscompress.pro` as described in [https://github.com/cnr-isti-vclab/nexus/blob/master/INSTALL.md](https://github.com/cnr-isti-vclab/nexus/blob/master/INSTALL.md). `nxsbuild`, `nxsedit` and `nxsview` are working perfectly fine! What am I missing here?

Many thanks,
Christoph

**Comment by ponchio** [comment]
Hi, there was a missing file in nxscompress.pro, it should be fixed now.
