### ISSUE TITLE
About  QEM  effect！

### ISSUE THREAD

**Issue by zero406-CC** [cnr-isti-vclab/nexus#153]
Hi there but i got a problem about nexus，i build a  big model about 2GB with 40 million triganles(.stl file extension),when i run the  nxsview.exe to check the result ,i found the qem effect is not good enough  when the viewer show the coarse level，because my laptop hardware is not good enough so i can not set up the  parameters like Mtri or Gpu too big，Is there any suggestion to improve the QEM effect.
Looking forward to receiving your reply ！Thank U.Here is a pic:
<a href="https://postimg.cc/mhQRb3Jy" target="_blank"><img src="https://i.postimg.cc/mhQRb3Jy/1.png" alt="1"/></a><br/><br/>
<a href="https://postimg.cc/ctMNXZwb" target="_blank"><img src="https://i.postimg.cc/ctMNXZwb/2.png" alt="2"/></a><br/><br/>
<a href="https://postimg.cc/FkQ4y1dS" target="_blank"><img src="https://i.postimg.cc/FkQ4y1dS/3.png" alt="3"/></a><br/><br/>
<a href="https://postimg.cc/Z92ZqwJV" target="_blank"><img src="https://i.postimg.cc/Z92ZqwJV/4.png" alt="4"/></a><br/><br/>

**Comment by ponchio** [comment]
Nexus uses a quadric simplification algorithm, and this technique does not performs well on cad models.

I never found a simplification/remeshing algorithm (with the additional requirement to be able to lock certain triangles/vertices) designed for CAD models. If one was available I could integrate it into the building software.

Some changes in building parameters might improve the situation (it can be very model dependent), so if you send me a sample, I can have a look at it. (ponchio@gmail.com).

**Comment by zero406-CC** [comment]
Thanks for your reply！I'll check the source code and give it a try，thank u。
