### ISSUE TITLE
when you zoom out, Nexux will delete more vertexes and triangles？

### ISSUE THREAD

**Issue by atlas1119** [cnr-isti-vclab/nexus#155]
I know , Nexus is split in blocks using different resolution and swaps betwenn resolutions when data arrive, when you zoom in and out or even pan.
But I do not know ，when you zoom out, Nexux will delete more vertexes and triangles？

**Comment by ponchio** [comment]
No, everything is precomputed, just different resolutions of the same model are swapped in and out.

The quality of the result depends on the quality of the simplification algorithm. Quadrics (the algorithm used in Nexus) is not a good choice for CAD models for example (Not that I have found better alternatives), in particular is not able to do remeshing, so some triangles might just be removed.
