### ISSUE TITLE
multiple materials and texture errors

### ISSUE THREAD

**Issue by xiang7970** [cnr-isti-vclab/nexus#156]
Hello, I found that when processing obj models, if there are multiple materials, it will cause texture errors, and it seems that only one image is used for repeated texturing. Can you please provide more details about your question?
raw：
![image](https://github.com/cnr-isti-vclab/nexus/assets/50948080/3013e0a2-225c-440e-b88a-cfb7113cb070)
![image](https://github.com/cnr-isti-vclab/nexus/assets/50948080/99b6c301-a590-4039-8ff9-6800f0c87fef)
mtl：
![image](https://github.com/cnr-isti-vclab/nexus/assets/50948080/a3937f5e-7a9a-498d-8429-fb365725ecdf)
nxz：
![image](https://github.com/cnr-isti-vclab/nexus/assets/50948080/05fefa50-29b5-4fe3-a422-1d2d3807208c)

**Comment by ponchio** [comment]
Could you send me a sample object, I will look into it.

**Comment by ponchio** [comment]
Thanks for the sample, I made a test with the master branch latest commit and it seems to work properly (Ubuntu).

Which version are you using? Command line?

**Comment by xiang7970** [comment]
I am using the win11 operating system, version Nexus_4.3. I have not compiled the latest code and think that may be necessary to resolve the issue. I have also used the pyMeshLab save_current_mesh method and encountered the same problem. Thank you for your help. When will the next version be released and will the pyMeshLab Nexus plugin be updated accordingly?

**Comment by xiang7970** [comment]
Thank you, I have successfully recompiled the latest code from the master branch on Win11 and it is now functioning properly. I am extremely grateful for your assistance. Could you please provide me with a detailed response regarding when the next version will be released and integrated into pyMeshLab?

**Comment by xiang7970** [comment]
Hello, thank you for the information. I will make sure to follow the steps you provided to download the new version of pyMeshLab from the 'actions' tab and find the executables in the artifacts section. I understand that there is no fixed schedule for the next release of pyMeshLab and you are not responsible for it. Thank you for your response.
