### ISSUE TITLE
Not simplified model at the highest LOD

### ISSUE THREAD

**Issue by roman-nikolaev** [cnr-isti-vclab/nexus#16]
Hello,
Thank you for sharing this library and tools, great work!
Would it be possible to use an original model geometry at the highest LOD?

**Comment by ponchio** [comment]
Hi, 
        sorry but I don't understand what the question exactly is.
The resolution on the model  when rendering depends on a few parameters which limits:

0) target rendering error (in pixels)
1) amount of memory required
2) amount of GPU memory required
3) amount of triangle rendered
4) Minimum FPS (depending on the computer capabilities).

The library is configured with some heuristic to guarantee decent performamances on a common PC.
You can change the parameters to sacrifice speed and memory usage for better quality.
Set the FPS to 0 to disable the automatic paramters tuning.
In the C++ viewer the options are visible in the botttom right: increase memory and MT (max n. of triangle rendered in millions), you can make some test there before tuning the Jvascript version to understand what is limiting your rendering (you can also turn the info on to see how much memory is used, how many triangles, and current rendering error)

In 3DHOP you can use this functions:

setNexusTargetFps, getNexusTargetFps (in frames per seconds
setNexusTargetError, getNexusTargetError (in pixels 5 is a decent value, decrease for better resolution)
setNexusCacheSize, getNexusCacheSize (in bytes!)

In the Nexus Js viewer you can use this functions: (same as in 3DHOP)

Nexus.setTargetFps(this.ui.gl, fps);
Nexus.setMaxCacheSize(this.ui.gl, size);
Nexus.setTargetError(this.ui.gl, error);

I hope this helps...

Federico

**Comment by roman-nikolaev** [comment]
Hi Federico,
Thank you for the answer.
I will open it up a bit. Levels of details are pregenerated during creating nsx file. So, some of triangles are merged together.

Would it be possible to store inside the original geometry of a model inside nxs without merged triangles? So, first very rough level would be loaded, then rough, then fine looking model, then original geometry.

- Roman

**Comment by roman-nikolaev** [comment]
Ok. Great!
I just wanted to ensure that it works like this before taking the technology into use. In native 3d viewer I couldn't get camera close enough to my model to see that all the details are in place.
Thank you for the answers!
