### ISSUE TITLE
CLion Ubuntu build for nxsedit

### ISSUE THREAD

**Issue by Madg1c** [cnr-isti-vclab/nexus#17]
Wanted to add a bit of feedback for installing on Clion for ubuntu,

Within CMakeLists.txt I had to add glew to the include_directories ine:
include_directories(../../../vcglib ../../../vcglib/eigenlib  ../../../glew-2.1.0/include )

In settings>Build,Execution,Deployment>CMake I added to CMake options:
-DCMAKE_PREFIX_PATH=/home/parallels/Qt/5.11.1/gcc_64/lib/cmake

also I had to install corto:
download from GIT: https://github.com/cnr-isti-vclab/corto#libcorto
cmake ./
make
sudo make install
sudo ld config

Then the project complied successfully. Hope this saves a bit of time in the future.

**Comment by ponchio** [comment]
I will update the install instructions, thank you :)

**Comment by ascandaliato** [comment]
I'm installing on mac OS 0.14.5.

When running `sudo ld config` from the root `corto` directory, I get the error:

`ld: file not found: config`

I have to finish the linking part to complete the install for nexus:

When running ` make` In `nexus` root directory, I get the error:

```
ld: library not found for -lcorto
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [src/nxsbuild/nxsbuild] Error 1
make[1]: *** [src/nxsbuild/CMakeFiles/nxsbuild.dir/all] Error 2
make: *** [all] Error 2
```

Any help you can give for me to complete the linking process?

**Comment by ascandaliato** [comment]
I believe `sudo ld config` is supposed to be `sudo ldconfig` ??

**Comment by ascandaliato** [comment]
Update.

I was able to build the binaries for nxsbuild and nxsedit by using the qmake instructions. I was a bit confused because I thought it was optional to use qmake and that I could use cmake instead.
