### ISSUE TITLE
Loss in Color Saturation in Nexus 3D Compared to HTML Example

### ISSUE THREAD

**Issue by m-hassan-ad** [cnr-isti-vclab/nexus#171]
## Description  
There is a noticeable loss in color saturation in the Nexus 3D model when compared to the HTML example provided. This issue seems to have arisen due to the upgrade of Three.js in the library.

## Root Cause Analysis  
After conducting research and analysis, I found that:  
- The library uses Three.js version 1.59.  
- The repository code uses an older version of Three.js.  

The difference in Three.js versions appears to be causing discrepancies in color rendering.

## Steps to Reproduce  
1. Load the Nexus 3D example using the library with Three.js version 1.59.  
2. Compare the color saturation with the HTML example provided in the repository using the older Three.js version.  

## Expected Behavior  
The color saturation in the Nexus 3D example should match that of the HTML example.

## Observed Behavior  
The color saturation in the Nexus 3D example appears significantly reduced compared to the HTML example.

With Version 1.59 

![image](https://github.com/user-attachments/assets/d96ef9f9-7f2a-4bff-bd03-80ec708c4c2d)

with Version 1.46
![image](https://github.com/user-attachments/assets/202ad465-9c12-4821-a324-0ea5c4cdf322)

**Comment by ponchio** [comment]
Last commit in threejsES6 branch fixes the issue.

The necessary step was to convert the texture in the colorspace specified in the material.
