### ISSUE TITLE
nxs and nxz won't load in THREE.js

### ISSUE THREAD

**Issue by Madg1c** [cnr-isti-vclab/nexus#18]
I've been testing a few models through processing compressing and displaying. The nxs and nxz files generated work through nsxview and appear in the HOP webviewer, but I can't get them to appear in the THREE.js webviewer. 

Has something changed to the format in the last build?

The gargo.nsz test file works but newly generated ones don't.

I should add, I'm not getting any errors back from the browser. The only way I know there is an issue is by looking at scene.children[3].instance. All the values here are 0.

UPDATE: I have it working now, not sure what's changed, but the files are loading nicely.

**Comment by ponchio** [comment]
I don't think anything has changed... might be a problem with the
positioning of the object?

in nexus_three.js line 22 and 23 the model is centered and scaled in the
unitary sphere.

I probably should have not done it...

Federico
