### ISSUE TITLE
can't get three.js example to work

### ISSUE THREAD

**Issue by foobarbecue** [cnr-isti-vclab/nexus#2]
I'm trying to run the example in html directory, which uses three.js. I'm serving it using WebStorm's built-in server and viewing it with Chrome 59.0.3063.4 dev (64-bit) on Windows 10 15063.14 . In the browser I just get a black screen and can't even open the Chrome dev tools. Any ideas? Is there a working example of nexus with three.js online somewhere I can compare with?

**Comment by ponchio** [comment]
There was a bug in the material with per vertex color, probably the number of webgl errors caused the dev tools.  

A working(!) example is here: http://pc-ponchio.isti.cnr.it/nexus/threejs.html

**Comment by foobarbecue** [comment]
great, thanks!

**Comment by foobarbecue** [comment]
Hm, I saw you might have fixed this in 709fae6, but tried it and didn't notice any difference; same behavior.

**Comment by ponchio** [comment]
The example seems to works everywhere I checked., if it's not just a cache problem, I will need your cooperation in debugging the problem with the Chrome dev tools... anything on the console?

**Comment by foobarbecue** [comment]
Interesting -- I uploaded the files to my web server, and it worked fine. Whenever I run with WebStorm locally, it doesn't. I am using an old version of WebStorm (2016.1.1). I managed to get into the debugger when I tried Firefox because it gave me the "a script is taking longer than expected" thing which had a "debug" button. It was stuck in an endless loop at line 342 -- p was increasing without bound and i was 0.

I'll let you close this issue if you like since the main problem is solved. I'm still curious as to why it doesn't work on WebStorm and I might find time to investigate further myself at some point.

**Comment by foobarbecue** [comment]
Found the root cause. The problem happened when i was serving on servers that do not have support for the http Range request (WebStorm built-in server and python SimpleHTTPserver). So when you send a request with a range, you get the whole file back, with a return code 200 rather than 206, and you end up stuck in an endless loop at line 340:

![image](https://cloud.githubusercontent.com/assets/854789/25067169/f5615ea0-21ef-11e7-9c5e-93e9745b007e.png)

I'll submit a patch that addresses this by checking that the return code is 206.
