### ISSUE TITLE
material not visible

### ISSUE THREAD

**Issue by dragonpoint** [cnr-isti-vclab/nexus#27]
I use THREE.OBJLoader2 loadMtl function load material and send the material to NexusObject constructor as the last parameter but only the model mesh shows up, no material visible.
Material is ok and right loaded  I'm very sure about that.
If I load the model from .obj file format and set the same material  every is all right.

**Comment by ponchio** [comment]
Could you provide example code? Would help me...

**Comment by dragonpoint** [comment]
function loadNxs()
            {
                 var strMTL = ......mtlFileName;
                var objLoader = new THREE.OBJLoader2();
                objLoader.loadMtl( strMTL, null, function(materials){
                    var strNxs = .......nxsFileName;
                    //materials 100% loaded and I test for .obj file is ok   It's a very simple jpg texture
                    var obj = new NexusObject(strNxs, g_renderer, nexus_render, materials);
                    obj.geometry.center();// not work maybe because the obj not finished loading
                    g_scene.add(obj);
                },
                function(xhr){
                    //XMLHttpRequest xhr

                }, 
                function(errorEvent){

                } );

            }

function nexus_render() 
{
        Nexus.beginFrame(g_renderer.context);
        g_renderer.render( g_scene, g_camera );
        Nexus.endFrame(g_renderer.context);
}
