### ISSUE TITLE
.nxz not show properly

### ISSUE THREAD

**Issue by dragonpoint** [cnr-isti-vclab/nexus#29]
[pjanic.zip](https://github.com/cnr-isti-vclab/nexus/files/2455186/pjanic.zip)

I'm under macOS Mojave 10.14  and I compiled the newest nexus from source code 2018-10-8. I got nxsbuild nxscompress command line and I converted .obj file to .nxs and .nxz.  the .nxs shows up fine but the .nxz file not showing up. 
I just replaced the model file name of your html example from gargo.nxz to my .nxz file but nothing shows up.  
I can load gargo.nxz in my test program. 
I can load both your .nxz and my .nxz file into nxsview app.

**Comment by ponchio** [comment]
It lokks like the problem is centering the object.

In the last commit i removed the autocentering code and moved it to the .html file, to be more compliant with threejs loading procedure.

In attachment an example:
[nxs centering example.zip](https://github.com/cnr-isti-vclab/nexus/files/2468340/nxs.centering.example.zip)

**Comment by dragonpoint** [comment]
I'm so sorry that the problem is because I didn't include corto.js in my project so ......
about how to center the object I have another solution without scaling model

//my program is showing a single model
function onLoadNxObjOver()
{
    var p = new THREE.Vector3();
    g_NexusObj.geometry.boundingBox.getCenter(p);
    //move objec to (0,0,0)
    g_NexusObj.position.set(-p.x, -p.y, -p.z);

    //not necessary but my special demands
    g_Obj = new THREE.Object3D();
    g_Obj.add(g_NexusObj);
    g_scene.add(g_Obj);

    fitCameraToObject( g_camera, g_NexusObj.geometry.boundingBox, 1 );

}

// my camera's init position  is (0,0,z?)
function fitCameraToObject( camera, boundingBox, offset ) 
{
    offset = offset || 1.25;
    const size = new THREE.Vector3();
    boundingBox.getSize(size);
    const maxDim = Math.max( size.x, size.y, size.z );
    const fov = camera.fov * ( Math.PI / 180 );
    cameraZ = Math.abs( maxDim * 2 * Math.tan( fov * 2 ) );
    cameraZ *= offset;
    camera.position.z = cameraZ;
}
