### ISSUE TITLE
nsxview missing .dlls

### ISSUE THREAD

**Issue by foobarbecue** [cnr-isti-vclab/nexus#3]
I'm trying to run nsxview.exe on Windows 59.0.3063.4 dev (64-bit), uncompressed from http://vcg.isti.cnr.it/nexus/download/Nexus_4.1.4.zip but I get lots of errors about missing .dlls:

Qt5Widgetsd.dll
Qt5OpenGLd.dll
Qt5Guid.dll
Qt5Cored.dll

I tried renaming Qt5Widgets.dll which comes in the .zip to Qt5Widgetsd.dll and the same for the other four, but then it complained about other .dlls.

Is there a prerequisite that I have to install, like qt dev tools or something?

**Comment by foobarbecue** [comment]
I guess the d means that this was a debug build. So I'm trying to build from source now, but need glew.

**Comment by ponchio** [comment]
Opps wrong executable. Tomorrow morning I will replace it. (or you can get
it from http://vcg.isti.cnr.it/3dhop/download.php, it might be a bit
outdated).

Yes you need glew (and vcglib), anyway.

,

**Comment by foobarbecue** [comment]
I got the glew .c and includes in place but now have lots of errors like C:\Users\aaron\Downloads\code\lib\glew\src\glew.c:-1: error: undefined reference to `_imp__wglGetProcAddress@4'

**Comment by foobarbecue** [comment]
I just tried the downloads at http://vcg.isti.cnr.it/nexus/download.php and they work now. Thanks for fixing this.
