### ISSUE TITLE
no issue but question

### ISSUE THREAD

**Issue by dragonpoint** [cnr-isti-vclab/nexus#30]
can anybody give some examples of wireframe mode and point cloud mode showing .nxs model ?
any advice is wellcome!

**Comment by ponchio** [comment]
I need to add these features... (it's not very complicated though).

**Comment by potenziani** [comment]
In the meanwhile you can take a look at this: http://repository.edition-topoi.org/collection/BSDP/single/0515/0
This repository provides the possibility to switch between triangle and pc visualization of Nexus models (but it is a little bit old project, and also it is the result of a quite relevant customization of the source code)

**Comment by ponchio** [comment]
It actually depends on how the reendering is done.

The Instance class has a renderMode property, which value can be either
FILL or POINT.

Wireframe needs to be developed though.

**Comment by dragonpoint** [comment]
I test renderMode with "POINT" value and everything looks fine
But I have other demands how to change point size? point color?   how to make points render better without flashing all the time?

If I use .obj model THREE.PointCloudMaterial  can do all that easily

**Comment by ponchio** [comment]
I have made the code better compatible with threejs point cloud rendering, adding the size and scale attribute.

In the html/threejs.html exmple how to change material (size and color).

`nexus_obj.material` = new THREE.PointsMaterial( {  size:1 } );

Let me know if this  works for you.

Could you me provide a .nxz point cloud example that flashes? I will investigate and hopefully solve.

**Comment by ponchio** [comment]
According to the lines of code you wrote, the points should be full green,
while on the video they have a degree of transparency (which
seems to change randomly).

Could you provide a snippet or code so that I can replicate the issue?

**Comment by dragonpoint** [comment]
my code is a little complex and are separated in many files. 
please check the following url for my project

http://67.218.154.3

source js files explain :  
useNexus.js  main loading nxs/nxz file
initScene.js  init threejs

**Comment by dragonpoint** [comment]
Sorry I found a new issue please check the gun model it's not showing ok

javascript error
WebGL: INVALID_VALUE: drawArrays: first or count < 0

**Comment by ponchio** [comment]
Hi, found a bug in the point cloud rendering. Fixed. (nexus.js)

**Comment by dragonpoint** [comment]
thanks a lot !  bug fixed!
