### ISSUE TITLE
nxsbuild 1GB .obj file assert failed

### ISSUE THREAD

**Issue by dragonpoint** [cnr-isti-vclab/nexus#32]
Assertion failed: (n>0 && max_size[0]>0 && max_size[1]>0), function PackInt, file /Users/long/Documents/work/myprojects/NodeJS/nexus/nexus-master/../vcglib/vcg/space/rect_packer.h, line 259.

I want to convert a very big(1GB)  .obj model to .nxs but failed.  I tried to use more memory but not work.

nxsbuild  c.obj           failed
nxsbuild -r 8000 c.obj     failed too

Mac 10.14  16GB memory

**Comment by ponchio** [comment]
It looks like a texture packaging problem, not a memory problem

Fragmented texture parametrization + simplification can cause some
problems. Could you send me a test, so I can debug it?

**Comment by dragonpoint** [comment]
please check the following url for models It's a little big 

https://pan.baidu.com/s/1wbzZ9Rtc6Qeo-Mr4-xazeA

**Comment by ponchio** [comment]
Hi, I could not replicate the issue on this dataset. It just works....

**Comment by dragonpoint** [comment]
Hi ponchio

thank you very much

I downloaded the newest source code and recompiled everything and tested the same model It really works now! no problem anymore!
