### ISSUE TITLE
Large OBJ File Hangs

### ISSUE THREAD

**Issue by hunterfortuin** [cnr-isti-vclab/nexus#33]
When trying to convert a relatively large OBJ file (364mb) nxsbuild is hanging.

```bash
Womp-iMac:Desktop hunterfortuin$ nxsbuild cargo_bottle33.obj -r 5000
Reading cargo_bottle33.obj
Vertices read: 1360086
Colors read: 1
faces read: 2723700
Components: mesh colors
Normals enabled
Colors enabled
Creating level 0
Creating level 1
Creating level 2
Creating level 3
```

It got through the the first three levels in about an hour but it's been stuck for an additional hour on the fourth level.

Here is the file: [cargo_bottle33.obj](https://www.dropbox.com/s/mqnd0nm4qwlrkgk/cargo_bottle33.obj?dl=0)

Attempted on both an OSX 10.13.6 machine and an Ubuntu 18.04 machine.

**Comment by ponchio** [comment]
I can't replicate the problem...  but I have noticed some simplification artefacts (which needs to be investigated anyway) but not hanging.

Might be a problem with the vcg library?

I'm using the devel branch of the vcg: https://github.com/cnr-isti-vclab/vcglib/tree/devel.

The simplification of CAD models is problematic for many reasons, maybe tuning a few parameters (in term of splitting the models, shape of the triangles, etc, might improve the result.

**Comment by ponchio** [comment]
A few bugs related to nxsbuilder looping somewhere in the simplification process have been ironed out, might have solved this issue.
