### ISSUE TITLE
Considering using Nexus to stream game's world object

### ISSUE THREAD

**Issue by tylerssn** [cnr-isti-vclab/nexus#37]
I'm porting a game from its native client to a web version. The biggest hurdle is latency in streaming the world map to the client (it's quite large so I don't want to download the map to the client).

If I can convert the world map to a Nexus-compatible object, can I stream only the portion of the object that I want to render within the client?

**Comment by ponchio** [comment]
Ciao,

     in theory yes, it should work, but you have first to understand how
nexus works and in case modify the client to best adapt to your case.

Nexus attempts to keep in memory a whole representation of the object with
different resolution depending on the view point... it depends on:

1) the part of the model already downloaded,
2) the RAM cache available
3) the GPU cache available
4) the maximum amount of triangles rendering budged
5) the geometrical error in rendering desidered.

It doesn't take into account occlusion, which for indoor maps could be much
more important than everything else.
Your map will have a different resolution and it will be difficult, should
you need it to guarantee that the most resoluted version is rendered.
Building the Nexus dataset will simpyfy the model, depending on the texture
fragmentation and the kind of model (cad model for example are terrible),
the result might be bad.

On the other hand you can test it easily, you will always have a
representation of the model, so jumping around the map would not leave you
with empty parts,
compression is available, so it would improve speed.

Ciao,

Federico
