### ISSUE TITLE
lower resolution levels contain geometry artifacts

### ISSUE THREAD

**Issue by ascandal** [cnr-isti-vclab/nexus#39]
Testing converting sample `obj` and `stl` files to `nxs` with `nxsbuild`.

While loading into `Threejs`, the lower resolution levels show geometry artifacts in the form of long spikes coming off of the model. see attached snapshot.

The spike artifacts are resolved as higher resolution levels are loaded and rendered.

Any ideas what could be causing this? My initial idea is overflow of vertex coordinate calculation.

<img width="862" alt="snapshot-nxs-AH-64-level3-snapshot" src="https://user-images.githubusercontent.com/10603297/59391997-eb758080-8d2a-11e9-9cac-8afc9eecd9d8.png">

**Comment by ponchio** [comment]
Some parameter in the simplification algorithm were prone to numerical instabilities. FIxed.
