### ISSUE TITLE
how can I extract textured meshes? The export .ply function is not textured T_T

### ISSUE THREAD

**Issue by AbegNext** [cnr-isti-vclab/nexus#42]

**Comment by RowanHall** [comment]
bump.

**Comment by mcallieri** [comment]
Nexus is intended as a "rendering-only" format. It was never meant to be used for data exchange and storage. Some data can be extracted, but some is lost (in the sense that is stored inside the structure differently from tits original format). If you are the owner of the model, and created the nexus, you still have the original. If you are processing data coming from someone else, ask them the original data. If you have downloaded third party data from an online viewer without asking permission to reuse it, then you definitely should not get the data :)
