### ISSUE TITLE
Per vertex position displacement

### ISSUE THREAD

**Issue by ascandal** [cnr-isti-vclab/nexus#45]
What are the limitations for manipulating the geometry once loaded in THREEjs?

Particularly I want to be able to displace the vertex positions, with a different displacement per vertex. The issues I am facing are as follows.

* How to gain access to the geometry position attributes to read and update their value?
* with no compression it looks like the vertex buffer is Uint8Array when I expected Float32Array?

Thank you

**Comment by ponchio** [comment]
The vertex buffer is an Uint8Array, just create a 		

var v = new Float32Array(buffer, 0, nv*3);

the coordinates of the vertex are at the beginning of the buffer and you can change the coordinates
as you wish.

The nodes are loaded while rendering, so you need to update everything each frame, or keep track of which node has been updated.
