### ISSUE TITLE
duplicate key `decodeDiff` in meco.js `MeshCoder`

### ISSUE THREAD

**Issue by ascandal** [cnr-isti-vclab/nexus#46]
The same key name `decodeDiff` is defined twice in `MeshCoder` for `meco.js`

**Comment by ponchio** [comment]
You are right, I was probably just testing which one was the faster, and forgot to remove one.

On the other hand the meco.js is a compatibility layer with some old models while Corto is just way better. It will just be removed in a short while and forgotten.
