### ISSUE TITLE
Error 429

### ISSUE THREAD

**Issue by loicroybon** [cnr-isti-vclab/nexus#47]
Hello. I'm trying to stream a "large" dataset (not very large in reality, only 80 Mb after NXZ compression). I took sample the code of this page, just changing the file path.

--> After few seconds, my server crashes with a 429 error... Is there an explaniation/solution ?

**Comment by loicroybon** [comment]
PS : if you want to try to reproduce the error, my file is here : https://drive.google.com/open?id=1C1hNTf-HX19iDCW3MVesmXjeOeqpC1WE

**Comment by ponchio** [comment]
Hi Loic,

 It looks it's an http error: 429 TOO MANY REQUESTS.
The streaming algorithm for Nexus splits the model in chunks which are
individually requested,  (~50-100K per block in your case).

The server might be rate limiting the number of http requests... it looks
like you need to change the config of your http server.

Ciao,

Federico
