### ISSUE TITLE
rendering in three.js gives strange results

### ISSUE THREAD

**Issue by mathib** [cnr-isti-vclab/nexus#49]
When I load my own converted PLY mesh into .nxz in the three.js app you've shared (https://github.com/cnr-isti-vclab/nexus/tree/master/html), I notice that about 90% of the texture is not acceptable. When I view the same .nxz in nxsviewer, everything looks good. See attached image:
![wall-renderingIssue](https://user-images.githubusercontent.com/22965460/63642161-8e4b6300-c6bb-11e9-85e6-04b4fb9e57f0.PNG)

**Comment by ponchio** [comment]
The image on the right looks like is using color per vertex...
could you share the 3d model with me (along with the command line used for
nxsbuilder?), so I can investigate the problem?

Thanks.

**Comment by mathib** [comment]
Hi, indeed, that could be the issue. I don't know the material properties that should be changed for this..

It kinda looks similar as having the mesh in Meshlab with the following settings: 
![image](https://user-images.githubusercontent.com/22965460/63751974-aafcbc00-c8b0-11e9-8bac-0a63a757b5a2.png)

**Comment by ponchio** [comment]
Try using the -c (no vertex colors) in the nxsbuild commandline....

**Comment by mathib** [comment]
Thanks, that solved my issue!
