### ISSUE TITLE
CMake scripts

### ISSUE THREAD

**Issue by cdcseacave** [cnr-isti-vclab/nexus#5]
Do you plan including CMake building scripts? I can help with that if needed.

**Comment by ponchio** [comment]
Hi,
       Yes I was just about to add cmake scripts. Maybe you can test them
and help me fix them (I have no experience with cmake), thank you.

In the meanwhile I have extracted the mesh compression library to a
standalone exec/lib/jslib https://github.com/cnr-isti-vclab/corto
the main strength is decompression speed.

Thanks,

Federico

**Comment by ponchio** [comment]
Hi,
      I have added the scripts, I'm a bit unsure on how to deal with glew...

F.
