### ISSUE TITLE
nexus point cloud in three.js - resize points fails

### ISSUE THREAD

**Issue by mathib** [cnr-isti-vclab/nexus#51]
When I load a NXZ point cloud in three.js, and I change the points material size, I don't see anything changing. I use the following:

` nexus_obj.material = new THREE.PointsMaterial( {  size:500, transparent: false, opacity:0.25 , vertexColors: THREE.VertexColors } ); `

Am I missing something here? Thanks!

**Comment by mathib** [comment]
This was tested on your demo `church_pointcloud.nxz` file and on another local file..

**Comment by ponchio** [comment]
The point size in the material was effectively ignored. FIxed.
