### ISSUE TITLE
any way to convert back from .nxs?

### ISSUE THREAD

**Issue by Fxlr8** [cnr-isti-vclab/nexus#6]
Hi, i wonder is there a way to convert model back from .nxs to any mesh format like obj or stl?

**Comment by ponchio** [comment]
Sure, nxsedit can be used to convert back to ply using the -p <filename.ply> option.

You can also extract a simpified version ( -l removes one level, basically halving the number of triangles), 
-s <size in MB> will extract a ply approximately that big,  or -t <triangles> specifies the number of faces in the output.

Basically you can use Nexus as an out-of-core simplification.

You might want to remove duplicated vertices in meshlab on the output.

**Comment by RowanHall** [comment]
Hi! I did this, but the ply file did not include the texture, is there any way to include the texture?

**Comment by ponchio** [comment]
I don't think that's actually possible: the texture coordinates were not present in the original model...
I'm not sure I understood what are you trying to do.

**Comment by RowanHall** [comment]
when I view the model with nsxview it displays the texture on the model, I would like to export the model and the texture for viewing and editing in other applications.

**Comment by ponchio** [comment]
The texture is butchered beyond reconstruction by the nxsbuilder processing, and makes it not really usable in any editing software. I didn't bother to export it.

**Comment by RowanHall** [comment]
Is there any possibility of recovering it anyways?

**Comment by ponchio** [comment]
Yes, if you can render it you can export it. I need a good reason to spend my time doing that, though.

**Comment by RowanHall** [comment]
I'm wrapping nsxedit in Node, if you can give me an idea of how the texture is stored in the file i may be able to write the code to extract the texture myself.

**Comment by ponchio** [comment]
In nexus.js  the functions requestNodeTexture and loadNodeTexture load the
textures from the nxs. Basically the array mesh.textures contains the
offset of the texture (stored as a jpeg) for each node. For node n, the
beginning and end of the jpeg image in nxs are stored in mesh.textures[n]
and mesh.textures[n+1],
to load the in the browser the data returned from a partial httprequest is
loaded as source of an image: img.src = urlCreator.createObjectURL(blob)
and the url revoke once loaded the img.
urlCreator.revokeObjectURL(img.src); but I image in node.js the procedure
would be different.
