### ISSUE TITLE
problem loading multiple nxz files

### ISSUE THREAD

**Issue by ua4192** [cnr-isti-vclab/nexus#66]
Hi again.

One very simple question.

I am trying to load multiple nxz file in my scene, but as I have read in your examples it seems that you cannot pass any reference to the model at onNexusLoad function

```
var  models = [ "models/M5735067300200.nxz", "models/M5735035500100" ];
var nxzArray = [];
var nxz[0] = new NexusObject(models[0], onNexusLoad(), function() { redraw = true; }, renderer);
var nxz[1] = new NexusObject(models[0], onNexusLoad(), function() { redraw = true; }, renderer);
```

But at the loader you have to refernce to the nxz object so if you have multiple objects how to can deal with this?

I have tried to pass nexus_obj as argument  in onNexusLoad function but doesn't work.

Here the example of your function:

> function onNexusLoad() {
> 	sceneBox.union(nexus_obj.geometry.boundingBox)
> 	var center = sceneBox.getCenter(new THREE.Vector3());
> 	controls.target.set(center.x, center.y, center.z);
> 	controls.update();		
> 	var geometry = nexus_obj.geometry;
> 	redraw = true;
> 	nexus_obj.material = material;
> 	scene.add(nexus_obj_Arr[idx]);
> }

As loading nxz is async task I cannot use the same onNexusLoad function for multiple models.

Is there any way to achieve this?

Best regards

**Comment by ua4192** [comment]
Hi again.

I have found a workarround to load assets one per one waitinf until eachobject has been initialized.

I don'r know other better way, even I am quite sure it si.

Here my way:

Any hints?

```
var  models = [ "models/M5735067300200.nxz", "models/M5735035500100.nxz" ];
var index = 0;
var arr = [];
var nexus_obj;
var modelname;
nxzLoader(index)



function nxzLoader(index) {
	if (index == models.length) {
		console.log("end");
		var center = sceneBox.getCenter(new THREE.Vector3());
		controls.target.set(center.x, center.y, center.z);
		controls.update();
		return;
	} else {
		modelname = models[index];
		console.log("loading model nxz : ", modelname);
		nexus_obj = undefined;
		console.log("previous to constructor");
		nexus_obj = new NexusObject(modelname, onNexusLoad, function() { redraw = true; }, renderer);
		console.log("after to constructor");
		nexus_obj.name = modelname;
		console.log("after to constructor");
		//index ++;
	}
}


function onNexusLoad() {
	console.log("onNexusLoad begin");
	var nxzname = nexus_obj.name
	console.log("nxzname: " , nxzname);
	sceneBox.union(nexus_obj.geometry.boundingBox)
	
		
	var geometry = 	nexus_obj.geometry;
	redraw = true;
	nexus_obj.material = material;
	
	scene.add(nexus_obj);
	var pnexus_obj = new THREE.Mesh(nexus_obj.geometry);
	pnexus_obj.autoMaterial  = nexus_obj.autoMaterial;
	pnexus_obj.onAfterRender = nexus_obj.onAfterRender;
	pnexus_obj.material = pmaterial;
	pnexus_obj.name=nexus_obj.name;
	pickingScene.add(pnexus_obj);
	index ++;
	nxzLoader(index)
	console.log("onNexusLoad end");
}
```

**Comment by ponchio** [comment]
Sorry for being so late.
It was an oversight on my part not to add the instance parameter, I have added it.

The (ugly) but fastest solution would have been  this:

var nxz = [];
nxz[0] = new NexusObject(models[0], function() {  onNexusLoad(nxz[0]), function() { redraw = true; }, renderer);
nxz[1] = new NexusObject(models[1], function() { onNexusLoad(nxz[1]), function() { redraw = true; }, renderer);
