### ISSUE TITLE
Fatal error: Unespected missing image in disk and ram.

### ISSUE THREAD

**Issue by foobarbecue** [cnr-isti-vclab/nexus#7]
I am trying to use nxsbuild.exe to process a 354mb binary .ply generated by AGISoft PhotoScan, with 4 .jpg textures that are each 4096x4096. I get this:
```
C:\Users\aaron\Downloads\Nexus_4.1.5>nxsbuild.exe C:\Users\aaron\sfm\streambed\streambed.ply
Reading  "C:\\Users\\aaron\\sfm\\streambed\\streambed.ply"
Mesh with colors
Mesh with textures
Normals enabled.
Colors enabled.
Textures enabled.
Creating level 0
Fatal error: Unespected missing image in disk and ram.
```
I wonder what the problem is. The ply opens fine in CloudCompare and Meshlab, and I am not out of ram -- in fact I have 30gb free when it crashes.

**Comment by foobarbecue** [comment]
Interestingly, this does not happen on files less than about 50mb, and it also does not happen if I use an exe built with the debug libraries.

**Comment by ponchio** [comment]
This bug should have been fixed in the latest release, are you using the latest one?

**Comment by foobarbecue** [comment]
No, the problem occurred when using the 4.1.5 from http://vcg.isti.cnr.it/nexus/download.php , so closing. There is a similar problem that I'm having with the new code though (segfault on large models), will post another issue if I can't figure it out.

**Comment by foobarbecue** [comment]
The segfault happened because my .ply pointed to a texture file that did not exist.
