### ISSUE TITLE
nxsview cannot display textured models

### ISSUE THREAD

**Issue by XinShengHUST** [cnr-isti-vclab/nexus#70]
Hi, I try to use the nxsbuild to convert a textured model into a .nxs model. But when I inspect the .nxs model with nxsview, I can only get a mesh without textures.

All the texture atlas photos and models are in the same directory:"/home/shengxin/a/"

I build the .nxs model with **./nxsbuild /home/shengxin/a/a.obj** and I get:

- Reading /home/shengxin/a/a.obj
- Vertices read: 16609
- Colors read: 1
- Texture: a_material0000_map_Kd.png
- faces read: 25283
- Components: mesh colors textures
- Normals enabled
- Colors enabled
- Textures enabled
- Creating level 0
- Creating level 1
- Creating level 2
- Unifying normals
- Saving to file /home/shengxin/a/a.nxs

I  build the model with -m option to specify the mtl file, and  get similar result.
I also use the .ply textured model to build the .nxs model. Both the genarated .nxs model are textureless when inspected via nxsview. I'm not sure where I get it wrong. From the nxsbuild output, the textured model seems to be converted succcessfully. Can you help me with it? Thanks a lot.

Due to the size limits I upload the files seperately.
[a.zip](https://github.com/cnr-isti-vclab/nexus/files/4009174/a.zip)
[atlas_png.zip](https://github.com/cnr-isti-vclab/nexus/files/4009181/atlas_png.zip)

**Comment by XinShengHUST** [comment]
I use the older version Nexus 4.1.6 [https://github.com/cnr-isti-vclab/nexus/commit/8380155ffc48a0b407ce408432519f19a382216b](url) and I can view the textured model with nxsview now. It may have something to do with the lib glew. The new nxsview.pro do not include glew.c while the 4.1.6 does. By the way, the github version of glew cannot be successfully compiled. It's /src  directory doesn't include all the necessary files. If anybody got trouble with this lib, use the code from sourceforge.[https://sourceforge.net/projects/glew/files/glew/2.1.0/](url)

**Comment by ponchio** [comment]
Nxsview did not check for power of 2 textures when generating mipmaps. Sorry.
Fixed and committed.

Notice that using the -k options nxsbuild creates power of two textures (and can use a LOT more memory). 

Thanks for the hints about glew (for windows, I image), will have a look and make it easier to build. Thanks.
