### ISSUE TITLE
GL_INVALID_VALUE

### ISSUE THREAD

**Issue by YILINQ** [cnr-isti-vclab/nexus#72]
Hello! 
I have been using your library and it is really amazing!
Now I have a problem that when I use nxsbuild to build the .nxs file, it works fine and gives no errors or warnings. But when I try to view the model using nxsview, the viewer give me error message:
GL_INVALID_VALUE 
And it was reported by: /nexus/src/common/nexus.cpp:196
Could you please give me some advice on how to debug this? Thanks in advance!

**Comment by YILINQ** [comment]
It seems that I got a texture with larger size than GL_MAX_TEXTURE_SIZE:
my data size is:
width 16384
height 1024
While the GL_MAX_TEXTURE_SIZE is 3379
Could this be the possible cause of the problem?

**Comment by ponchio** [comment]
I very recently fixed a bug with the power of 2 textures texture option,
around those lines. Could you check the latest version?

Nexus butcher and reassemble textures, but I didn't specify a max texture
size and it's possible (for really fragmented parametrization
a very large texture is created (wasting a lot of space). Packing has not a
bias for square textures either, hence 16K x 1K.

If you can share the model with me (ponchio@gmail.com), I can investigate
the problem.

I am adding in these days a reparametrization step to fix this issue (so
your model would be a good test case).

**Comment by YILINQ** [comment]
Thank you for your quick reply! I think I used the latest version and figure it our that my problem is caused by GL_MAX_TEXTURE_SIZE, and: 
- 3379 is not the actual GL_MAX_TEXTURE_SIZE, it is an index of the macro
- This problem can be solved if I decompose a large model into smaller pieces.

Again, thank you for your quick reply and amazing work!

Sincerely,
Yilin
