### ISSUE TITLE
strange error in standard example

### ISSUE THREAD

**Issue by ua4192** [cnr-isti-vclab/nexus#74]
Hi 

I have downloaded the lastest version of nexus libraries from GITHUB and when I tried to open the threejs.html example it prompted me the following error:

The error is output each time you move the Scene ( pan | orbit | zoom )

It seems that the progressive loading|rendering is not working as expected.

wasm-0006df86-66:1 Uncaught (in promise) RuntimeError: memory access out of bounds
    at wasm-function[66]:0x5df6
    at wasm-function[69]:0x6baf
    at wasm-function[124]:0xbb2c
    at Object.decode (http://localhost:8080/nexus-master3/html/js/corto.em.js:149:11)
    at onmessage (http://localhost:8080/nexus-master3/html/js/corto.em.js:17:30)

**Comment by ponchio** [comment]
Hi, it looks like a problem with corto new emscriptem lib version, possibly
the colors changes.
I will debug the problem.

You can switch back to corto.js  (which is just a bit slower in
decompressing) in line 82 of nexus.js in the meanwhile.

**Comment by ponchio** [comment]
Seem it was a memory problem in corto.em.js,  I have fixed it in corto and update the nexus.js.
