### ISSUE TITLE
nxsbuild -z option appears not to work

### ISSUE THREAD

**Issue by foobarbecue** [cnr-isti-vclab/nexus#8]
The help for nxsbuild says that you can use the -z option to output a compressed nxz file instead of an nxs, but it appears to have no effect. I see there is also source for something called nxszip -- is that how we're supposed to make .nxz?

**Comment by foobarbecue** [comment]
I tried to build nxszip but it wants watch.cpp

**Comment by foobarbecue** [comment]
Oh I see, you use nxsedit instead of nxsbuild to make a .nxz . Help for nxsbuilt should be updated if it doesn't do zipping.

**Comment by potenziani** [comment]
Yes, you are right, to compress your nxs model you have to use the nxsedit exe. 
Thanks for your report, we are updating the help information right these days, with the next release everything should be ok.
