### ISSUE TITLE
examples errors and texture map will get error

### ISSUE THREAD

**Issue by umimori13** [cnr-isti-vclab/nexus#83]
Hi，I'm getting errors from the develop branch examples 

![threejs.html](https://user-images.githubusercontent.com/37163607/98515590-3429c400-22a6-11eb-9548-31f495c4e6fa.jpg)

and 

![raycast.html](https://user-images.githubusercontent.com/37163607/98515508-21af8a80-22a6-11eb-960c-95f73feddb50.jpg)

The second error also will be happend when I give null or no texture for the defalut material map

**Comment by ponchio** [comment]
Hi, there actually is no develop branch... currently I am developing the
master, and a version3 which is now supporting gltf (but forces me to
change the format).

Could you provide me a complete sample (html/js/ etc) so I can debug the
problem?

**Comment by umimori13** [comment]
oh it is master branch in /html/threejs.html and /html/racaster.html....
[nexus-master.zip](https://github.com/cnr-isti-vclab/nexus/files/5534251/nexus-master.zip)
this is the zip i just download from the master branch, it still have these problems

**Comment by ponchio** [comment]
A debug version made its way into master. Should be fixed it. now. Sorry.
