### ISSUE TITLE
wrong normals when change to MeshNormalMaterial

### ISSUE THREAD

**Issue by umimori13** [cnr-isti-vclab/nexus#84]
For some reasons, I need to switch the material to MeshNormalMaterial ( or only show no texture model) and change the material back . 

And this is what I get when I use the model gargo_mesh.ply
![Dingtalk_20201109173016](https://user-images.githubusercontent.com/37163607/98523804-4e1cd400-22b1-11eb-8bf7-380f7598285c.jpg)

The normals of the vertexes have changed.

So how to fix this?

**Comment by ponchio** [comment]
I think I need a sample to unaderstand what are you doing and what is the
problem...

**Comment by umimori13** [comment]
here is the example 
https://drive.google.com/file/d/1GljSpgR-pI3SyYi3Tixtd5FYDrPLtzXh/view?usp=sharing

**Comment by ponchio** [comment]
There was a bug for materials without colors used on meshes with colors. And a couple of other small fixes.
Thanks for the feedback and the example.
