### ISSUE TITLE
problems with updating texure values aftr first render

### ISSUE THREAD

**Issue by ua4192** [cnr-isti-vclab/nexus#88]
Hi Federico.

In my project I am using a custom shader (ShaderMaterial) in which I am using a texture in order to be able to change colors and visibility, and pickability depending on these texture values.

The first time when I set texture values it works as expected, but one the meshes have been rendered despites what I do with texture values there is no impact on my scene.

Is there any problem with this?

Here my glsl code:

```
<script id="vertexShader" type="x-shader/x-vertex">
			precision highp float;
			uniform float tSize;
			uniform mat4 matrix;
			uniform sampler2D texture;
			//uniform float time;
			uniform vec3 lPosition;
			uniform vec3 ambientColor; 
			uniform vec3 diffuseColor; 
			uniform vec3 specularColor;
			uniform float shininess; 
			//uniform float dsUuid; 
			in vec4 color;
			out vec3 vColor; 
			out float pn_UUID; 
			out float vspt;                       
			
			#include <common>                  
			#include <logdepthbuf_pars_vertex> 
			void main() {
				pn_UUID =  float( round( round(color.r*255.0)*65536.0 + round(color.g*255.0)*256.0 + round(color.b*255.0) ) );
				float tsize = tSize;
				ivec2 coords = ivec2( int(mod(pn_UUID, tsize)), int(floor(pn_UUID / tsize)) ) ;
				vec4 values = texelFetch(texture, coords, 0);                     	
				pn_UUID = pn_UUID;// + dsUuid;
				vec4 tPosition = matrix * vec4( position, 1.0 ); 
				vec3 icolor = values.xyz;
				vspt =  values.w;
				
				mat4 normalMatrix = transpose(inverse(viewMatrix));
				vec3 vPositionEye = vec3((viewMatrix * tPosition).xyz);
				vec3 vLPositionEye = vec3((viewMatrix * vec4( lPosition, 1.0 )).xyz);
				gl_Position = projectionMatrix * viewMatrix * tPosition;
				#ifdef PICKING
					vColor = tPosition.xyz;
				#else
					vec3 n = normalize(normal);
					vec3 e = - normalize( vPositionEye );
					vec3 l = normalize( lPosition - vPositionEye );
					vec3 r = normalize( reflect( - l, n ) ); 
					float diffuseLightWeighting = max( dot( n, l ), 0.0 ); 
					float specularLightWeighting = max( dot( r, e ), 0.0 );   
					specularLightWeighting = pow( specularLightWeighting, shininess );  
					lowp vec3 lightWeighting = (ambientColor*2.0 +                                    
						diffuseColor * diffuseLightWeighting +                                   
						specularColor * specularLightWeighting);			
					vColor = vec3( icolor.rgb *  lightWeighting.rgb);
				#endif
				#include <logdepthbuf_vertex>
			}
</script>

 <script id="fragmentShader" type="x-shader/x-fragment">
			precision highp float;
			uniform vec4 selectionColor;
			uniform float dsUuid; 
			in vec3 vColor;
			in float vspt;
			in float pn_UUID;
			out vec4 myColor;
			#include <logdepthbuf_pars_fragment>
			
			vec4 getVSPT(float vspto) {
				float vspt = round(vspto * 255.0);
				float v = floor(vspt / 128.0); 
				float spt = vspt - ( v * 128.0);
				float s = floor(spt / 64.0); 
				float pt = spt - ( s * 64.0 );
				float p = floor(pt / 32.0);
				float t = pt - (p * 32.0);
				return vec4( v, s, p, t );    
			}
			
			void main() {
				#include <logdepthbuf_fragment> 
				vec4 vsptArr = getVSPT(vspt);
				#ifdef PICKING
					if ( vsptArr[2] > 0.0  ) {
						myColor = vec4(vColor, pn_UUID + dsUuid);
						//myColor = vec4(vColor, vspt);
					} else {
						discard;
					}
				#else
					if ( vsptArr[0] > 0.0  ) {
						if ( vsptArr[1] > 0.0  ) {
							myColor = selectionColor;
						} else {
							myColor = vec4(vColor, 1.0);
						}
					} else {
						discard;
					}
					//myColor = vec4(1.0, 0.0, 0.0, 1.0);
				#endif
			}
</script>

```

When I change the values of my material.texture.value.image.data values I set needsUpdate attribute in my texture and also 
material.uniformsNeedUpdate = true but doesn't work.

Here my materials:

```
dsTextureDataMap[dsUuid] = new Uint8Array(side*side*4);
				for (var i=0; i<len; i++) {
					dsTextureDataMap[dsUuid][i*4] = textureData[i*3];     // real color r
					dsTextureDataMap[dsUuid][i*4+1] = textureData[i*3+1]; // real color g
					dsTextureDataMap[dsUuid][i*4+2] = textureData[i*3+2]; // real color b
					dsTextureDataMap[dsUuid][i*4+3] = 160; // vspt -->   vspt tttt    default value: p=32 + s=0 + v=128; 
				}
				
				dsTextureMap[dsUuid] = new THREE.DataTexture(dsTextureDataMap[dsUuid], side, side, THREE.RGBAFormat, THREE.UnsignedByteType)	
				dsTextureMap[dsUuid].magFilter = THREE.NearestFilter;
				dsTextureMap[dsUuid].minFilter = THREE.NearestFilter;
				dsTextureMap[dsUuid].needsUpdate = true;
				dsUniformsMap[dsUuid] = {
					"matrix": {value: nexus_obj.matrix},
					"selectionColor": { value: new THREE.Vector4(1.0, 1.0, 0.0, 0.5) },
					"lPosition": { value: camera.position },
					"ambientColor": { value: new THREE.Color(0x333333) },
					"diffuseColor": { value: new THREE.Color(0xaaaaaa) },
					"specularColor": { value: new THREE.Color(0xcccccc) },
					"shininess": { value: 2 },
					"tSize": {value: side},
					"texture": { value: dsTextureMap[dsUuid] },
					"dsUuid": { value: nexus_obj.userData.dsIndex}
				};
				//console.log(uniforms);

				dsMaterialMap[dsUuid] = new THREE.ShaderMaterial( {
					uniforms: dsUniformsMap[dsUuid],
					vertexShader: "#version 300 es\n" + document.getElementById( 'vertexShader' ).textContent,
					fragmentShader: "#version 300 es\n" + document.getElementById( 'fragmentShader' ).textContent,
					transparent: true,
					side: THREE.DoubleSide
				} );
				
				pdsMaterialMap[dsUuid] = new THREE.ShaderMaterial( {
					uniforms: dsUniformsMap[dsUuid],
					vertexShader: "#version 300 es\n#define PICKING\n" + document.getElementById( 'vertexShader' ).textContent,
					fragmentShader: "#version 300 es\n#define PICKING\n" + document.getElementById( 'fragmentShader' ).textContent,
					side: THREE.DoubleSide
				} );
```

The idea is quite simple. I have used this approach in other meshLoaders (glb, ply,obj) and it works.

Best regards

**Comment by ua4192** [comment]
Hi.

It was my fault.

Sorry.

**Comment by shubham0704** [comment]
@ua4192 I am also writing an application for coloring meshes using threejs for my research project. I am very new to nexus. Would you mind sharing any snippets that can help in this task?

**Comment by ponchio** [comment]
I don't think nexus is the right tool for editing meshes.
The main problem is that the format is 'multiresolution', you would need to
propagate the modifications (texture or color per vertex) to the other
resolutions.
At any given time you only have a partial representation of the object
(especially over the network) especially for large objects.
The only way to work would be to define a transfer function between
different levels (considering that we do not have a hierarchical structure,
so
each block would have multiple parents to update), and possibly to ensure
that the highest resolution is at least loaded in memory (so to transfer
the modifications).
This transfer could be done on the server or the client side but as you can
imagine a certain degree of coordination is needed.
Finally you need to save the modifications back to the server, taking care
to control the cache unloading of blocks.

Do you really have models so large that they do not fit in memory? That's
the only use case where this approach with nexus makes sense, and it would
be
extremely complicated.

**Comment by shubham0704** [comment]
Hi @ponchio thanks for replying. I am creating an annotation tool for large scale meshes. I was thinking of a simple work around. Previously I had imagined there was some mapping from low-resolution patch to high resolution patches and therefore we could propagate the color.
Currently, I am thinking of something more naive. We organize color in a volumetric way. Suppose I click at some location on the object. Then I will store a constant size bounding box of fix size with the click location as center on the client side. Whenever you load high/low resolution patch. If it is falls within that bounding box it gets that color.  Is this possible?

**Comment by ponchio** [comment]
In this paper http://vcg.isti.cnr.it/Publications/2019/PCDS19/ I developed an annotation tool for large meshes.
The approach is very similar: volumetric annotations and  decals. I am using a contour/vector approach, rather then a voxel/painting approach. 
The code consists of the rendering part (drawing twice the annotation mesh, volumetric shadow approach) and the
C++ server side code which creates the columetric mesh from the contour (but if you plan to use painting it could not be very useful.

**Comment by ponchio** [comment]
Write me on ponchio@gmail.com and we can arrange a call and discuss about the details (the code needs cleanup and might need some adjustment).

**Comment by shubham0704** [comment]
Sure, I will mail you. Thanks again.
