### ISSUE TITLE
raycaster wrong for my meshes

### ISSUE THREAD

**Issue by umimori13** [cnr-isti-vclab/nexus#91]
I am using the example 'raycast.html' to get each mesh point, but there is something wrong for this (see the GIF below ).
This is using the example for raycaster (when mouse enter it should be white)
I know it is right for the mesh 'gargo.nxz'. So it is confused for my mesh. I also test for my other meshes, and get the similar results .

![GIF 2020-11-23 16-33-05](https://user-images.githubusercontent.com/37163607/99941892-bc7d8e00-2da9-11eb-995c-44175d8353fa.gif)

I have send the example and one mesh and its ply file in 'model' folder.

By the way ,it seems not implemented in the threejsES6 of the raycaster

![Dingtalk_20201123164438](https://user-images.githubusercontent.com/37163607/99942849-47ab5380-2dab-11eb-8d09-62b34d73aa06.jpg)

**Comment by ponchio** [comment]
I have implemented raycasting in the threejsES6 branch, it works like other threejs objects, with the only caveat that recursive must be set to true (for the moment). I will have a look at the master branch.

**Comment by ponchio** [comment]
I am afraid I need a sample mesh (and possibly an extract of your relevant code) to debug the problem, I can't replicate the issue....

**Comment by umimori13** [comment]
I had sent you the example and the sample mesh to you in your email ponchio@gmail.com two days ago, may be you need check in your email

**Comment by umimori13** [comment]
I have tested your threejsES6 raycaster and it works right. Nice! 
By the way, do you mind using hot plugin in your threejsES6? Each time I change the code I need build and start again. The hot plugin can auto build the code so no need shutdown the start,build,and start again.
To use hot plugin, just 
```bash
npm i html-webpack-plugin
```
and add changes the configs in the ```webpack.config.js```
below the codes are edited from your ```webpack.config.js```
```
var webpack = require('webpack')
const HtmlWebpackPlugin = require('html-webpack-plugin')
const path = require('path')

module.exports = {
    entry: {
        main: './src/index.js',
    },

    output: {
        path: path.resolve(__dirname, 'dist'),
        filename: 'main.js',
    },
    devServer: {
        contentBase: path.join(__dirname, 'dist/'),
    },
    optimization: {
        minimize: false,
    },
    plugins: [
        new webpack.HotModuleReplacementPlugin(),
        new HtmlWebpackPlugin({
            title: 'Vark',
            template: __dirname + '/dist/index.html',
        }),
    ],
}
```



and then change the ```start:dev``` in ```scripts``` in the ```package.json``` ( why using ```start:dev```  but not ```start```?  )
```
"scripts":{
    ...
   "start": "webpack-dev-server --hot",
    ...
}

now it can rebuild auto when change the code after saving

**Comment by ponchio** [comment]
Sorry I can't find your email from 2 days ago (not in the inbox, not in the spam, not in the trash).

I have added html-webpack-plugin, very handy, thank you.

**Comment by umimori13** [comment]
well I left the link here too if you can't recive the email
https://drive.google.com/file/d/1qkdNx4Pym5z5U_bVGEmBGwFZqxrOVs4j/view?usp=sharing

**Comment by ponchio** [comment]
Fixed in master branch, (hopefully) and performances improved.
