### ISSUE TITLE
The exported NXZ model cannot be used

### ISSUE THREAD

**Issue by 1156150793** [cnr-isti-vclab/nexus#92]
The model provided by the project can be used, but the model exported by window cannot be used on the web side. There is no difference between the two. Why?

**Comment by ponchio** [comment]
Sorry I think I need some details to understand the problem:

"exported by window" means create using the executables under windows? or something else?

"cannot be used on the web side" what is the problem? Any error in the web console?

**Comment by 1156150793** [comment]
Yes, using executable file creation under windows, no syntax error, but the model can not be loaded------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Federico&amp;nbsp;Ponchio&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年11月25日(星期三) 晚上9:37
收件人:&nbsp;&quot;cnr-isti-vclab/nexus&quot;<nexus@noreply.github.com&gt;;
抄送:&nbsp;&quot;1156150793&quot;<1156150793@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [cnr-isti-vclab/nexus] The exported NXZ model cannot be used (#92)

**Comment by ponchio** [comment]
Ok, we got the first point,  now onto the second point:

I need some details on the "cannot be used on the web side". If you open the developer  tools in chrome (F12), you will probably find some error in the console...

I need a description of the problem more precise than "the model can not be loaded".

In any case you can send me a sample (code and nxs/z model) and I will have a look at it.

**Comment by 1156150793** [comment]
The console did not report an error，The top part is the model I exported, and the bottom part is the model of the project。





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cnr-isti-vclab/nexus"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月26日(星期四) 凌晨1:24
收件人:&nbsp;"cnr-isti-vclab/nexus"<nexus@noreply.github.com&gt;;
抄送:&nbsp;"? .文幾"<1156150793@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [cnr-isti-vclab/nexus] The exported NXZ model cannot be used (#92)





 
Ok, we got the first point,  now onto the second point:
 
I need some details on the "cannot be used on the web side". If you open the developer  tools in chrome (F12), you will probably find some error in the console...
 
I need a description of the problem more precise than "the model can not be loaded".
 
In any case you can send me a sample (code and nxs/z model) and I will have a look at it.

**Comment by 1156150793** [comment]
Hello. Now there is another problem. How to load both model and texture in browser?

**Comment by ponchio** [comment]
Both model and texture are inside the .nxs / .nxz (the compressed version)
file...
