### ISSUE TITLE
Using nxsbuild to convert PLY with texture to NXS

### ISSUE THREAD

**Issue by 1156150793** [cnr-isti-vclab/nexus#94]
After conversion, use three.js The texture of the displayed model becomes rough.The model is too big to be sent

![FI$R9L(Y0~R) ~_F$21`CU](https://user-images.githubusercontent.com/61828020/101611280-45e8bd80-3a44-11eb-8b18-273b06bab322.png)

**Comment by ponchio** [comment]
Most probably the model contains both color per vertex and texture.
Use the -c option in nxsbuild and the colors wont be saved,  the texture should be visible instead.

**Comment by 1156150793** [comment]
> 该模型很可能同时包含每个顶点的颜色和纹理。
> 在nxsbuild中使用-c选项，将不会保存颜色，而是应显示纹理。

I try to use the model on the Internet to transform and display it with nxsview. The effect is not as good as the original model. Do you have any suggestions?
Links to models：https://www.artec3d.com/3d-models/doom-combat-scene
![`1FKCF)ITST}QB1BJF@3FFI](https://user-images.githubusercontent.com/61828020/101727661-df20de00-3aef-11eb-9d16-a9f59db8f772.png)
![~MM}KH26QY}R2U~JVWP9Q(X](https://user-images.githubusercontent.com/61828020/101727679-e811af80-3aef-11eb-8c69-d913597fea47.png)

**Comment by 1156150793** [comment]
I'm going to try to modify the map, but I can only modify the normal map, not the color map. If you have any suggestions, please let me know

**Comment by ponchio** [comment]
Again it looks like the model is displaying the per vertex colors and not the texture color.
Remove the color component from the model before using nxsbuild (or just use the -c options in nxsbuild: it will drop the color attribute).

**Comment by 1156150793** [comment]
How to use the color of the texture in the model converted with the -c option in nxsbuild？

**Comment by ponchio** [comment]
I realized what is the problem: the OBJ download, at the link you shared, has a texture, while the PLY has NO texture, only color per vertex, and I didn't realize that, sorry.
Generally you can open the model in MeshLab to verify which component are actually present and what you should expect.

Here you can see the OBJ model converted:

https://visual.ariadna-infrastructure.eu/3d/e0586adf909aac5251367b79040efd44

(this is not using threejs materials, so the final appearance will be a little different).
