### ISSUE TITLE
problem with shader material and cloud of points

### ISSUE THREAD

**Issue by ua4192** [cnr-isti-vclab/nexus#95]
Hi Federico.

I am currently trying to load a cloud point nxz file generated by thyese commands:

```
nxsbuild.exe M2529330000000.ply -o M2529330000000.nxs -n -c -p
Reading M2529330000000.ply
Components: pointcloud
Creating level 0
Creating level 1
Creating level 2
Saving to file M2529330000000.nxs

nxsedit.exe M2529330000000.nxs -o M2529330000000.nxz -z
Reading M2529330000000.nxs
Vertex quantization step: 24.0718
Texture quantization step: 0.25
Saving with flag: 4 (compressed with CORTO)
Textures: 0
Saving to file M2529330000000.nxz
```

In my THREEJS scene I am trying to use a ShaderMaterial and try to make gl_PointSize variable depending on distance to camera

In this shader the size is fixed, but it is not working, nothing is visible:

```
var vertexShader = `
	#include <common>                  
	#include <logdepthbuf_pars_vertex> 
	void main() {
		vec4 tPosition = vec4( position, 1.0 ); 
		gl_PointSize = 100.0;
		gl_Position = projectionMatrix * viewMatrix * tPosition;
		
		#include <logdepthbuf_vertex>
	}
`;

var fragmentShader = `
	precision highp float;
	#include <logdepthbuf_pars_fragment>
	void main() {
		#include <logdepthbuf_fragment> 
		gl_FragColor = vec4(1.0, 0.0, 0.0, 1.0);
	}
`;

var shadermaterial = new THREE.ShaderMaterial({
	vertexShader: vertexShader,
	fragmentShader: fragmentShader,
	side: THREE.DoubleSide
});
```

If I use a PointMaterial it works:

material = new THREE.PointsMaterial( { color: 0xff0000, size: 20} );

Is it possible to use a ShaderMaterial for PointClouds?

My filling is that when I use a ShaderMaterial the mode is automatically set to FILL and not to POINTS and this is the reason of the problem.

Many thanks in advanced.

**Comment by ua4192** [comment]
Hi.

FInally I had to modify nesus_three.js library and add my own condition in order to diferenciate between Meshes and PointClouds:
 on function onAfterRender(renderer, scene, camera, geometry, material, group)
I modified the condition instance.mode = attr.size ? "POINT" : "FILL"; by my own getting this property from geometry attribute


Best regards

**Comment by ponchio** [comment]
I think I found a decent solution.

If the model has no triangles, always render in mode POINT, if the material has the isPointsMaterial == true, render as point cloud, otherwise render in FILL mode.

Your model has no triangles so it should render correctly, and you might apply your point-cloud shader also to meshes, if you set the "isPointsMaterial" property to true.

**Comment by ponchio** [comment]
I fixed it in the master branch.
