### ISSUE TITLE
Assertion `0' failed when converting a large ply file

### ISSUE THREAD

**Issue by bklaric** [cnr-isti-vclab/nexus#98]
I'm doing some stress testing on Nexus and I'm converting some large .ply models into .nxs. I tried converting a ~5 GB model and after about an hour of running, the process exits with an error message. This is all the output I get from running nxsbuild:
```
Reading /ply/model.ply
Components: mesh colors
Normals enabled
Colors enabled
Creating level 0
Creating level 1
nxsbuild: /nexus/src/nxsbuild/../../../vcglib/vcg/simplex/vertex/base.h:134: static bool vcg::VertexArityMax<UserTypes, A, B, C, D, E, F, G, H, I, J, K, L>::DeleteBitFlag(int) [with UserTypes = AUsedTypes; A = vcg::vertex::VFAdj; B = vcg::vertex::Coord3f; C = vcg::vertex::Normal3f; D = vcg::vertex::TexCoord2f; E = vcg::vertex::Color4b; F = vcg::vertex::Mark; G = vcg::vertex::BitFlags; H = vcg::DefaultDeriver; I = vcg::DefaultDeriver; J = vcg::DefaultDeriver; K = vcg::DefaultDeriver; L = vcg::DefaultDeriver]: Assertion `0' failed.
```
Additional details:

- Everything works fine with smaller .ply files. The largest one tested is 2.5 GB.
- nxsbuild was running inside a Docker container. This was the command used: `docker run -i -v /home/branimir/ply:/ply nexus-image:latest /nexus/build/src/nxsbuild/nxsbuild /ply/model.ply -o /ply/model.nxs`
- Docker image was built from the latest master branch.
- The 5 GB ply model that failed was created by duplicating and translating all vertices and corresponding faces of the 2.5 GB ply model. This same approach was tested on a smaller 50 MB model and the conversion to nxs was successful.
- I've made sure that I have enough storage space (>30 GB).

Do you have an idea on what might be causing the error?

**Comment by ponchio** [comment]
It looks like it is a problem in the simplification algorithm, but hard to tell what is the reason.

Could you share the model? I will try to duplicate the issue...

**Comment by bklaric** [comment]
I'm not allowed to share the original model that caused the error, but I've managed to reproduce it using the gargo.ply available from the Nexus website. I'll email you the download links separately.

**Comment by ponchio** [comment]
Managed to solve the issue: well hidden in VCG a flag a static value is used to allocate new flags, but managed to lock only the initialization of the simplification algorithm.
